### PR TITLE
Feature/abennani feature

### PR DESCRIPTION
**Pull request by ayoubben**

### CODE REVIEW

**Comment by zedtux** [comment]
@ayoubben the code looks good to me, nice job.

Nevertheless when I try to run the tests, I have the following error:

```
~/Developments/rails-exercise • rake                                                                                                                                                                                                                                                                                                                rvm:ruby-2.2.3@exercice
/Users/guillaumehain/.rvm/rubies/ruby-2.2.3/bin/ruby -I/Users/guillaumehain/.rvm/gems/ruby-2.2.3@exercice/gems/rspec-core-3.4.1/lib:/Users/guillaumehain/.rvm/gems/ruby-2.2.3@exercice/gems/rspec-support-3.4.1/lib /Users/guillaumehain/.rvm/gems/ruby-2.2.3@exercice/gems/rspec-core-3.4.1/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb
Coverage report generated for RSpec to /Users/guillaumehain/Developments/rails-exercise/coverage. 24 / 112 LOC (21.43%) covered.
/Users/guillaumehain/Developments/rails-exercise/spec/models/model_spec.rb:3:in `<top (required)>': uninitialized constant Model (NameError)
	from /Users/guillaumehain/.rvm/gems/ruby-2.2.3@exercice/gems/rspec-core-3.4.1/lib/rspec/core/configuration.rb:1361:in `block in load_spec_files'
	from /Users/guillaumehain/.rvm/gems/ruby-2.2.3@exercice/gems/rspec-core-3.4.1/lib/rspec/core/configuration.rb:1359:in `each'
	from /Users/guillaumehain/.rvm/gems/ruby-2.2.3@exercice/gems/rspec-core-3.4.1/lib/rspec/core/configuration.rb:1359:in `load_spec_files'
	from /Users/guillaumehain/.rvm/gems/ruby-2.2.3@exercice/gems/rspec-core-3.4.1/lib/rspec/core/runner.rb:102:in `setup'
	from /Users/guillaumehain/.rvm/gems/ruby-2.2.3@exercice/gems/rspec-core-3.4.1/lib/rspec/core/runner.rb:88:in `run'
	from /Users/guillaumehain/.rvm/gems/ruby-2.2.3@exercice/gems/rspec-core-3.4.1/lib/rspec/core/runner.rb:73:in `run'
	from /Users/guillaumehain/.rvm/gems/ruby-2.2.3@exercice/gems/rspec-core-3.4.1/lib/rspec/core/runner.rb:41:in `invoke'
	from /Users/guillaumehain/.rvm/gems/ruby-2.2.3@exercice/gems/rspec-core-3.4.1/exe/rspec:4:in `<main>'
/Users/guillaumehain/.rvm/rubies/ruby-2.2.3/bin/ruby -I/Users/guillaumehain/.rvm/gems/ruby-2.2.3@exercice/gems/rspec-core-3.4.1/lib:/Users/guillaumehain/.rvm/gems/ruby-2.2.3@exercice/gems/rspec-support-3.4.1/lib /Users/guillaumehain/.rvm/gems/ruby-2.2.3@exercice/gems/rspec-core-3.4.1/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb failed
```

I've solved this by removing the file `spec/models/model_spec.rb` (I guess the creation of this file was a mistake), then I have the following failing tests:

```
~/Developments/rails-exercise • rake                                                                                                                                                                                                                                                                                                                rvm:ruby-2.2.3@exercice
/Users/guillaumehain/.rvm/rubies/ruby-2.2.3/bin/ruby -I/Users/guillaumehain/.rvm/gems/ruby-2.2.3@exercice/gems/rspec-core-3.4.1/lib:/Users/guillaumehain/.rvm/gems/ruby-2.2.3@exercice/gems/rspec-support-3.4.1/lib /Users/guillaumehain/.rvm/gems/ruby-2.2.3@exercice/gems/rspec-core-3.4.1/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb
........FFF*....*

Pending: (Failures listed here are expected and do not affect your suite's status)

  1) SubTask add some examples to (or delete) /Users/guillaumehain/Developments/rails-exercise/spec/models/sub_task_spec.rb
     # Not yet implemented
     # ./spec/models/sub_task_spec.rb:4

  2) User add some examples to (or delete) /Users/guillaumehain/Developments/rails-exercise/spec/models/user_spec.rb
     # Not yet implemented
     # ./spec/models/user_spec.rb:4


Failures:

  1) TasksController GET #index responds successfully with an HTTP 200 status code
     Failure/Error: get :index

     NoMethodError:
       undefined method `authenticate!' for nil:NilClass
     # /Users/guillaumehain/.rvm/gems/ruby-2.2.3@exercice/gems/devise-3.5.3/lib/devise/controllers/helpers.rb:116:in `authenticate_user!'
     # ./spec/controllers/tasks_controller_spec.rb:24:in `block (3 levels) in <top (required)>'

  2) TasksController GET #index renders the index template
     Failure/Error: get :index

     NoMethodError:
       undefined method `authenticate!' for nil:NilClass
     # /Users/guillaumehain/.rvm/gems/ruby-2.2.3@exercice/gems/devise-3.5.3/lib/devise/controllers/helpers.rb:116:in `authenticate_user!'
     # ./spec/controllers/tasks_controller_spec.rb:30:in `block (3 levels) in <top (required)>'

  3) TasksController GET #index loads all of the tasks into @tasks
     Failure/Error: get :index

     NoMethodError:
       undefined method `authenticate!' for nil:NilClass
     # /Users/guillaumehain/.rvm/gems/ruby-2.2.3@exercice/gems/devise-3.5.3/lib/devise/controllers/helpers.rb:116:in `authenticate_user!'
     # ./spec/controllers/tasks_controller_spec.rb:40:in `block (3 levels) in <top (required)>'

Finished in 0.47559 seconds (files took 1.69 seconds to load)
17 examples, 3 failures, 2 pending

Failed examples:

rspec ./spec/controllers/tasks_controller_spec.rb:23 # TasksController GET #index responds successfully with an HTTP 200 status code
rspec ./spec/controllers/tasks_controller_spec.rb:29 # TasksController GET #index renders the index template
rspec ./spec/controllers/tasks_controller_spec.rb:34 # TasksController GET #index loads all of the tasks into @tasks

Coverage report generated for RSpec to /Users/guillaumehain/Developments/rails-exercise/coverage. 35 / 86 LOC (40.7%) covered.
/Users/guillaumehain/.rvm/rubies/ruby-2.2.3/bin/ruby -I/Users/guillaumehain/.rvm/gems/ruby-2.2.3@exercice/gems/rspec-core-3.4.1/lib:/Users/guillaumehain/.rvm/gems/ruby-2.2.3@exercice/gems/rspec-support-3.4.1/lib /Users/guillaumehain/.rvm/gems/ruby-2.2.3@exercice/gems/rspec-core-3.4.1/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb failed
```

**Comment by ayoubben** [comment]
thank you.

I didn't the tests, i thought it wasn't requested.

**Comment by zedtux** [comment]
It wasn't, and on purpose. When you work on a project with existing tests, you should take care of them :)

**Comment by ayoubben** [comment]
Of course, thank you.

**Pull request closed without merging**
